module.exports = [
  { id: 'mum-dad', left: 'Things to do with your mum', right: 'Things to do with your dad' },
  { id: 'hot-cold', left: 'Hot', right: 'Cold' },
  { id: 'overrated-underrated', left: 'Overrated', right: 'Underrated' },
  { id: 'vacation-cost', left: 'Cheap vacation', right: 'Expensive vacation' },
  { id: 'superpower', left: 'Boring superpower', right: 'Exciting superpower' },
  { id: 'first-date', left: 'Bad first date idea', right: 'Great first date idea' },
  { id: 'conversation', left: 'Small talk topic', right: 'Deep conversation topic' },
  { id: 'movie-rating', left: 'Kid-friendly movie', right: 'Definitely not kid-friendly movie' },
  { id: 'costume-effort', left: 'Low-effort costume', right: 'High-effort costume' },
  { id: 'food-occasion', left: 'Everyday food', right: 'Special-occasion food' },
  { id: 'hobby-volume', left: 'Quiet hobby', right: 'Loud hobby' },
  { id: 'risk', left: 'Safe bet', right: 'Risky bet' },
  { id: 'outfit', left: 'Casual outfit', right: 'Formal outfit' },
  { id: 'pet', left: 'Common pet', right: 'Unusual pet' },
  { id: 'weekend', left: 'Relaxing weekend', right: 'Exhausting weekend' },
  { id: 'gift', left: 'Cheap gift', right: 'Extravagant gift' },
  { id: 'spice', left: 'Mild spice level', right: 'Extremely spicy' },
  { id: 'exercise', left: 'Easy exercise', right: 'Intense workout' },
  { id: 'personality-activity', left: 'Introvert activity', right: 'Extrovert activity' },
  { id: 'era', left: 'Old-fashioned', right: 'Futuristic' },
];
