module.exports = [
  { id: 'beach', name: 'Beach' },
  { id: 'casino', name: 'Casino' },
  { id: 'space-station', name: 'Space Station' },
  { id: 'school', name: 'School' },
  { id: 'hospital', name: 'Hospital' },
  { id: 'airplane', name: 'Airplane' },
  { id: 'circus-tent', name: 'Circus Tent' },
  { id: 'submarine', name: 'Submarine' },
  { id: 'bank', name: 'Bank' },
  { id: 'restaurant', name: 'Restaurant' },
  { id: 'movie-studio', name: 'Movie Studio' },
  { id: 'polar-station', name: 'Polar Research Station' },
  { id: 'pirate-ship', name: 'Pirate Ship' },
  { id: 'amusement-park', name: 'Amusement Park' },
  { id: 'museum', name: 'Museum' },
  { id: 'embassy', name: 'Embassy' },
  { id: 'cathedral', name: 'Cathedral' },
  { id: 'university', name: 'University' },
  { id: 'supermarket', name: 'Supermarket' },
  { id: 'night-club', name: 'Night Club' },
  { id: 'corporate-party', name: 'Corporate Party' },
  { id: 'ski-resort', name: 'Ski Resort' },
];
