module.exports = [
  { id: 'giraffe-yoga', text: 'A confused giraffe doing yoga' },
  { id: 'worst-superhero', text: "The world's worst superhero" },
  { id: 'pizza-alive', text: 'A pizza that came to life' },
  { id: 'grandma-motorcycle', text: 'Grandma riding a motorcycle' },
  { id: 'alien-school', text: "An alien's first day at school" },
  { id: 'cat-dog', text: 'A cat pretending to be a dog' },
  { id: 'last-unicorn', text: 'The last unicorn on Earth' },
  { id: 'robot-love', text: 'A robot falling in love' },
  { id: 'dinosaur-coffee', text: 'A dinosaur ordering coffee' },
  { id: 'awkward-high-five', text: "The world's most awkward high-five" },
  { id: 'ghost-dark', text: "A ghost who's afraid of the dark" },
  { id: 'snowman-vacation', text: 'A snowman on vacation in summer' },
  { id: 'pirate-water', text: "A pirate who's afraid of water" },
  { id: 'vampire-garlic-bread', text: 'A vampire allergic to garlic bread' },
  { id: 'slowest-race-car', text: "The world's slowest race car" },
  { id: 'wizard-lost-wand', text: 'A wizard who lost his wand' },
  { id: 'mermaid-swim', text: "A mermaid who can't swim" },
  { id: 'useless-power', text: 'A superhero with a completely useless power' },
  { id: 'angriest-teddy-bear', text: "The world's angriest teddy bear" },
  { id: 'dragon-fire', text: "A dragon who's scared of fire" },
  { id: 'knight-dragons', text: 'A knight who is afraid of dragons' },
  { id: 'octopus-juggle', text: 'An octopus trying to juggle' },
  { id: 'nervous-ninja', text: "The world's most nervous ninja" },
  { id: 'penguin-cold', text: "A penguin who can't stand the cold" },
  { id: 'time-traveler-traffic', text: 'A time traveler stuck in traffic' },
];
