// Fandom pack: characters, creatures, items, and concepts pulled from the
// higher/lower fandom pool, chosen because they're describable or actable
// out within a few seconds — the same bar the original everyday-object list
// (Elephant, Pirate, Astronaut...) was held to.
module.exports = [
  { id: 'luffy', text: 'Luffy' },
  { id: 'zoro', text: 'Zoro' },
  { id: 'devil-fruit', text: 'Devil Fruit' },
  { id: 'ichigo', text: 'Ichigo Kurosaki' },
  { id: 'soul-reaper', text: 'Soul Reaper' },
  { id: 'hollow', text: 'Hollow' },
  { id: 'natsu', text: 'Natsu Dragneel' },
  { id: 'erza', text: 'Erza Scarlet' },
  { id: 'naruto', text: 'Naruto Uzumaki' },
  { id: 'sasuke', text: 'Sasuke Uchiha' },
  { id: 'titan', text: 'Titan' },
  { id: 'levi', text: 'Levi Ackerman' },
  { id: 'light-yagami', text: 'Light Yagami' },
  { id: 'death-note-item', text: 'Death Note' },
  { id: 'tanjiro', text: 'Tanjiro Kamado' },
  { id: 'nezuko', text: 'Nezuko Kamado' },
  { id: 'deku', text: 'Izuku Midoriya' },
  { id: 'all-might', text: 'All Might' },
  { id: 'gojo', text: 'Satoru Gojo' },
  { id: 'denji', text: 'Denji' },
  { id: 'edward-elric', text: 'Edward Elric' },
  { id: 'gon', text: 'Gon Freecss' },
  { id: 'goku', text: 'Son Goku' },
  { id: 'jinwoo', text: 'Sung Jinwoo' },
  { id: 'shadow-monarch', text: 'Shadow Monarch' },
  { id: 'sunny', text: 'Sunny' },
  { id: 'ainz', text: 'Ainz Ooal Gown' },
  { id: 'kirito', text: 'Kirito' },
  { id: 'rem', text: 'Rem' },
  { id: 'bam', text: 'Bam' },
  { id: 'kim-dokja', text: 'Kim Dokja' },
  { id: 'saitama', text: 'Saitama' },
  { id: 'anya', text: 'Anya Forger' },
  { id: 'loid', text: 'Loid Forger' },
  { id: 'gandalf', text: 'Gandalf' },
  { id: 'frodo', text: 'Frodo Baggins' },
  { id: 'one-ring', text: 'The One Ring' },
  { id: 'hobbit', text: 'Hobbit' },
  { id: 'voldemort', text: 'Lord Voldemort' },
  { id: 'hogwarts-word', text: 'Hogwarts' },
  { id: 'quidditch', text: 'Quidditch' },
  { id: 'james-bond-word', text: 'James Bond' },
  { id: 'daenerys', text: 'Daenerys Targaryen' },
  { id: 'iron-throne', text: 'Iron Throne' },
  { id: 'lightsaber', text: 'Lightsaber' },
  { id: 'darth-vader', text: 'Darth Vader' },
  { id: 'sandworm', text: 'Sandworm' },
  { id: 'geralt', text: 'Geralt of Rivia' },
  { id: 'katniss', text: 'Katniss Everdeen' },
  { id: 'percy-jackson-word', text: 'Percy Jackson' },
  { id: 'aslan', text: 'Aslan' },
];
