// Fandom pack, v2: expanded per user feedback — with 5 players and 5-minute
// rounds you burn through the original ~50 fast, so this now covers most
// franchises in the higher/lower pool with 3-8 entries each (main cast,
// notable side characters, iconic items/creatures), not just one or two.
// Everything here should still be describable or actable within a few
// seconds, the same bar the original everyday-object list held to.
module.exports = [
  { id: 'luffy', text: 'Luffy' },
  { id: 'zoro', text: 'Zoro' },
  { id: 'devil-fruit', text: 'Devil Fruit' },
  { id: 'ichigo', text: 'Ichigo Kurosaki' },
  { id: 'soul-reaper', text: 'Soul Reaper' },
  { id: 'hollow', text: 'Hollow' },
  { id: 'natsu', text: 'Natsu Dragneel' },
  { id: 'erza', text: 'Erza Scarlet' },
  { id: 'naruto', text: 'Naruto Uzumaki' },
  { id: 'sasuke', text: 'Sasuke Uchiha' },
  { id: 'titan', text: 'Titan' },
  { id: 'levi', text: 'Levi Ackerman' },
  { id: 'light-yagami', text: 'Light Yagami' },
  { id: 'death-note-item', text: 'Death Note' },
  { id: 'tanjiro', text: 'Tanjiro Kamado' },
  { id: 'nezuko', text: 'Nezuko Kamado' },
  { id: 'deku', text: 'Izuku Midoriya' },
  { id: 'all-might', text: 'All Might' },
  { id: 'gojo', text: 'Satoru Gojo' },
  { id: 'denji', text: 'Denji' },
  { id: 'edward-elric', text: 'Edward Elric' },
  { id: 'gon', text: 'Gon Freecss' },
  { id: 'goku', text: 'Son Goku' },
  { id: 'jinwoo', text: 'Sung Jinwoo' },
  { id: 'shadow-monarch', text: 'Shadow Monarch' },
  { id: 'sunny', text: 'Sunny' },
  { id: 'ainz', text: 'Ainz Ooal Gown' },
  { id: 'kirito', text: 'Kirito' },
  { id: 'rem', text: 'Rem' },
  { id: 'bam', text: 'Bam' },
  { id: 'kim-dokja', text: 'Kim Dokja' },
  { id: 'saitama', text: 'Saitama' },
  { id: 'anya', text: 'Anya Forger' },
  { id: 'loid', text: 'Loid Forger' },
  { id: 'gandalf', text: 'Gandalf' },
  { id: 'frodo', text: 'Frodo Baggins' },
  { id: 'one-ring', text: 'The One Ring' },
  { id: 'hobbit', text: 'Hobbit' },
  { id: 'voldemort', text: 'Lord Voldemort' },
  { id: 'hogwarts-word', text: 'Hogwarts' },
  { id: 'quidditch', text: 'Quidditch' },
  { id: 'james-bond-word', text: 'James Bond' },
  { id: 'daenerys', text: 'Daenerys Targaryen' },
  { id: 'iron-throne', text: 'Iron Throne' },
  { id: 'lightsaber', text: 'Lightsaber' },
  { id: 'darth-vader', text: 'Darth Vader' },
  { id: 'sandworm', text: 'Sandworm' },
  { id: 'geralt', text: 'Geralt of Rivia' },
  { id: 'katniss', text: 'Katniss Everdeen' },
  { id: 'percy-jackson-word', text: 'Percy Jackson' },
  { id: 'aslan', text: 'Aslan' },
  { id: 'nami', text: 'Nami' },
  { id: 'sanji', text: 'Sanji' },
  { id: 'chopper', text: 'Tony Tony Chopper' },
  { id: 'nico-robin', text: 'Nico Robin' },
  { id: 'portgas-ace', text: 'Portgas D. Ace' },
  { id: 'shanks', text: 'Shanks' },
  { id: 'boa-hancock', text: 'Boa Hancock' },
  { id: 'trafalgar-law', text: 'Trafalgar Law' },
  { id: 'rukia', text: 'Rukia Kuchiki' },
  { id: 'renji', text: 'Renji Abarai' },
  { id: 'toshiro', text: 'Toshiro Hitsugaya' },
  { id: 'aizen', text: 'Sosuke Aizen' },
  { id: 'byakuya', text: 'Byakuya Kuchiki' },
  { id: 'yoruichi', text: 'Yoruichi Shihoin' },
  { id: 'gray', text: 'Gray Fullbuster' },
  { id: 'lucy-heartfilia', text: 'Lucy Heartfilia' },
  { id: 'happy-cat', text: 'Happy' },
  { id: 'wendy-marvell', text: 'Wendy Marvell' },
  { id: 'kakashi', text: 'Kakashi Hatake' },
  { id: 'itachi', text: 'Itachi Uchiha' },
  { id: 'gaara', text: 'Gaara' },
  { id: 'sakura', text: 'Sakura Haruno' },
  { id: 'nine-tailed-fox', text: 'Nine-Tailed Fox' },
  { id: 'eren', text: 'Eren Yeager' },
  { id: 'mikasa', text: 'Mikasa Ackerman' },
  { id: 'armin', text: 'Armin Arlert' },
  { id: 'erwin', text: 'Erwin Smith' },
  { id: 'colossal-titan', text: 'Colossal Titan' },
  { id: 'l-lawliet', text: 'L' },
  { id: 'ryuk', text: 'Ryuk' },
  { id: 'misa', text: 'Misa Amane' },
  { id: 'zenitsu', text: 'Zenitsu Agatsuma' },
  { id: 'inosuke', text: 'Inosuke Hashibira' },
  { id: 'giyu', text: 'Giyu Tomioka' },
  { id: 'muzan', text: 'Muzan Kibutsuji' },
  { id: 'bakugo', text: 'Katsuki Bakugo' },
  { id: 'uraraka', text: 'Ochaco Uraraka' },
  { id: 'todoroki', text: 'Shoto Todoroki' },
  { id: 'endeavor', text: 'Endeavor' },
  { id: 'yuji', text: 'Yuji Itadori' },
  { id: 'megumi', text: 'Megumi Fushiguro' },
  { id: 'nobara', text: 'Nobara Kugisaki' },
  { id: 'sukuna', text: 'Ryomen Sukuna' },
  { id: 'power', text: 'Power' },
  { id: 'aki-hayakawa', text: 'Aki Hayakawa' },
  { id: 'makima', text: 'Makima' },
  { id: 'alphonse', text: 'Alphonse Elric' },
  { id: 'roy-mustang', text: 'Roy Mustang' },
  { id: 'winry', text: 'Winry Rockbell' },
  { id: 'philosophers-stone', text: "Philosopher's Stone" },
  { id: 'killua', text: 'Killua Zoldyck' },
  { id: 'hisoka', text: 'Hisoka Morow' },
  { id: 'kurapika', text: 'Kurapika' },
  { id: 'vegeta', text: 'Vegeta' },
  { id: 'piccolo', text: 'Piccolo' },
  { id: 'bulma', text: 'Bulma' },
  { id: 'frieza', text: 'Frieza' },
  { id: 'super-saiyan', text: 'Super Saiyan' },
  { id: 'cha-haein', text: 'Cha Hae-In' },
  { id: 'beru', text: 'Beru' },
  { id: 'kai-shadowslave', text: 'Kai' },
  { id: 'rebecca-shadowslave', text: 'Rebecca' },
  { id: 'yoo-joonghyuk', text: 'Yoo Joonghyuk' },
  { id: 'rachel-tog', text: 'Rachel' },
  { id: 'albedo', text: 'Albedo' },
  { id: 'demiurge', text: 'Demiurge' },
  { id: 'subaru', text: 'Subaru Natsuki' },
  { id: 'emilia', text: 'Emilia' },
  { id: 'puck-catspirit', text: 'Puck' },
  { id: 'asuna', text: 'Asuna Yuuki' },
  { id: 'sinon', text: 'Sinon' },
  { id: 'klein-sao', text: 'Klein' },
  { id: 'genos', text: 'Genos' },
  { id: 'tatsumaki', text: 'Tatsumaki' },
  { id: 'damian-desmond', text: 'Damian Desmond' },
  { id: 'yor-forger', text: 'Yor Forger' },
  { id: 'bond-the-dog', text: 'Bond the Dog' },
  { id: 'samwise', text: 'Samwise Gamgee' },
  { id: 'gollum', text: 'Gollum' },
  { id: 'legolas', text: 'Legolas' },
  { id: 'aragorn', text: 'Aragorn' },
  { id: 'sauron', text: 'Sauron' },
  { id: 'hermione', text: 'Hermione Granger' },
  { id: 'ron-weasley', text: 'Ron Weasley' },
  { id: 'dumbledore', text: 'Albus Dumbledore' },
  { id: 'snape', text: 'Severus Snape' },
  { id: 'dobby', text: 'Dobby' },
  { id: 'hagrid', text: 'Hagrid' },
  { id: 'q-bond', text: 'Q' },
  { id: 'm-bond', text: 'M' },
  { id: 'moneypenny', text: 'Moneypenny' },
  { id: 'jaws-bond', text: 'Jaws' },
  { id: 'jon-snow', text: 'Jon Snow' },
  { id: 'tyrion', text: 'Tyrion Lannister' },
  { id: 'cersei', text: 'Cersei Lannister' },
  { id: 'arya', text: 'Arya Stark' },
  { id: 'direwolf', text: 'Direwolf' },
  { id: 'luke-skywalker', text: 'Luke Skywalker' },
  { id: 'han-solo', text: 'Han Solo' },
  { id: 'leia', text: 'Princess Leia' },
  { id: 'yoda', text: 'Yoda' },
  { id: 'chewbacca', text: 'Chewbacca' },
  { id: 'r2d2', text: 'R2-D2' },
  { id: 'paul-atreides', text: 'Paul Atreides' },
  { id: 'duncan-idaho', text: 'Duncan Idaho' },
  { id: 'chani', text: 'Chani' },
  { id: 'baron-harkonnen', text: 'Baron Harkonnen' },
  { id: 'ciri', text: 'Ciri' },
  { id: 'yennefer', text: 'Yennefer' },
  { id: 'jaskier', text: 'Jaskier' },
  { id: 'peeta', text: 'Peeta Mellark' },
  { id: 'effie', text: 'Effie Trinket' },
  { id: 'mockingjay', text: 'Mockingjay' },
  { id: 'annabeth', text: 'Annabeth Chase' },
  { id: 'grover', text: 'Grover Underwood' },
  { id: 'medusa-pj', text: 'Medusa' },
  { id: 'minotaur', text: 'Minotaur' },
  { id: 'jadis', text: 'Jadis, the White Witch' },
  { id: 'mr-tumnus', text: 'Mr. Tumnus' },
  { id: 'lucy-pevensie', text: 'Lucy Pevensie' }
];
