module.exports = [
  { id: 'elephant', text: 'Elephant' },
  { id: 'pirate', text: 'Pirate' },
  { id: 'astronaut', text: 'Astronaut' },
  { id: 'birthday-cake', text: 'Birthday Cake' },
  { id: 'volcano', text: 'Volcano' },
  { id: 'superhero', text: 'Superhero' },
  { id: 'snowman', text: 'Snowman' },
  { id: 'dinosaur', text: 'Dinosaur' },
  { id: 'wizard', text: 'Wizard' },
  { id: 'roller-coaster', text: 'Roller Coaster' },
  { id: 'penguin', text: 'Penguin' },
  { id: 'ninja', text: 'Ninja' },
  { id: 'mermaid', text: 'Mermaid' },
  { id: 'robot', text: 'Robot' },
  { id: 'kangaroo', text: 'Kangaroo' },
  { id: 'campfire', text: 'Campfire' },
  { id: 'octopus', text: 'Octopus' },
  { id: 'firefighter', text: 'Firefighter' },
  { id: 'skateboard', text: 'Skateboard' },
  { id: 'unicorn', text: 'Unicorn' },
  { id: 'submarine', text: 'Submarine' },
  { id: 'cowboy', text: 'Cowboy' },
  { id: 'tornado', text: 'Tornado' },
  { id: 'vampire', text: 'Vampire' },
  { id: 'lighthouse', text: 'Lighthouse' },
  { id: 'jellyfish', text: 'Jellyfish' },
  { id: 'knight', text: 'Knight' },
  { id: 'hot-air-balloon', text: 'Hot Air Balloon' },
  { id: 'mummy', text: 'Mummy' },
  { id: 'scuba-diver', text: 'Scuba Diver' },
  { id: 'sandcastle', text: 'Sandcastle' },
  { id: 'werewolf', text: 'Werewolf' },
  { id: 'parachute', text: 'Parachute' },
  { id: 'flamingo', text: 'Flamingo' },
  { id: 'magician', text: 'Magician' },
  { id: 'igloo', text: 'Igloo' },
  { id: 'race-car-driver', text: 'Race Car Driver' },
  { id: 'chef', text: 'Chef' },
  { id: 'gladiator', text: 'Gladiator' },
  { id: 'yeti', text: 'Yeti' },
  { id: 'surfer', text: 'Surfer' },
  { id: 'volcano-eruption', text: 'Volcano Eruption' },
  { id: 'jack-in-the-box', text: 'Jack-in-the-Box' },
  { id: 'lumberjack', text: 'Lumberjack' },
  { id: 'octopus-hug', text: 'Octopus Hug' },
  { id: 'ghost', text: 'Ghost' },
  { id: 'snake-charmer', text: 'Snake Charmer' },
  { id: 'tightrope-walker', text: 'Tightrope Walker' },
  { id: 'sumo-wrestler', text: 'Sumo Wrestler' },
  { id: 'beekeeper', text: 'Beekeeper' },
];
